# -*- coding: utf-8 -*-
"""ENGR 326 Project - Jaxon Cooper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1piuUL5sr8codX2Hx_BIDhWVr4rz8wqoY
"""

import numpy as np
import scipy
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

### PARAMETERS ###

## SUMMIT ROTORCRAFT SYSTEMS (SRS) ROTORCRAFT SPECIFICATIONS ##

m = 1300 # maximum gross mass of rotorcraft, kg
r = 4.2 # radius of rotor, m
P_SL = 310000 # sea level turboshaft power
eff = 0.92 # mechanical efficiency
d_ex = 0.85 # turboshaft density exponent
pf = 1.1 # induced power factor

## EXTERNAL PARAMETERS ##

g = 9.81 # gravity, m/s^2
d0 = 1.225 # sea level density, kg/m^3
T0 = 288.15 # ISA standard temperature, K
L = -0.0065 # ISA temperature lapse rate, K/m
R = 287.05 # ISA specific gas constant for air, J/(kg*K)

## CALCUALTED VALUES FROM SPECIFICATIONS ##

W = m*g # maximum gross weight of rotorcraft, N
A = np.pi*(r**2) # disk area, m^2

## REQUIRED CONSTANTS ##

roc_crit = 0.51 # minimum (critical) climb rate, m/s
tau = 5 # time constant for vertical speed dynamics, s

### FUNCTIONS ###

def density(h): # density vs altitude
  T = T0+L*h
  exponent = (-1 - g/(L*R))
  return d0*(T/T0)**exponent

def P_avail(h): # available power, W
  dens = density(h)
  return eff*P_SL*(dens/d0)**d_ex

def P_req(h): # required power, W
  dens = density(h)
  vi = np.sqrt(W/(2*dens*A)) # induced velocity, m/s
  return pf*W*vi

def v_ss(h): # steady-state rate of climb, m/s
  return (P_avail(h)-P_req(h)) / W

### ODE AND SOLVING ###

def climb_dyn(t,y): # second order climb dynamics ODE
  h,v = y
  h = max(0.0,h)
  dhdt = v # roc, m/s
  dvdt = (v_ss(h)-v)/tau # acceleration, m/s^2
  return [dhdt,dvdt]

t_span = (0,3600) # 0 to 1 hr
y0 = [0,0]
sol = solve_ivp(climb_dyn,t_span,y0, max_step=1) # solve with RK45

t_vals = sol.t # t values
h_vals = sol.y[0] # h values
roc_vals = sol.y[1] # v values

above = (roc_vals >= roc_crit) # find when roc initially passes critical
first_above = np.argmax(above) # find the first roc value past critical

below = np.where((roc_vals <= roc_crit) & (np.arange(len(roc_vals)) > first_above))[0] # all points after climb where roc <= roc_crit

i = below[0] # finds the first time roc falls below roc_crit
h_limit = h_vals[i]
t_limit = t_vals[i] / 60


print(f"Service-ceiling altitude ≈ {h_limit:.0f} m ")
print(f"Threshold ROC TTC ≈ {t_limit:.1f} min")

### PLOTTING ###

fig, ax1 = plt.subplots()

line1, = ax1.plot(t_vals,h_vals,label= "$Altitude$",color='blue')
ax1.set_xlabel("Time (s)")
ax1.set_ylabel("Altitude (m)",);

plt.axhline(y=h_limit, color='black', linestyle='--')
plt.plot(t_limit*60, h_limit, marker='o', color='black')

ax2 = ax1.twinx()
line2, = ax2.plot(t_vals,roc_vals,label= "$VROC$",color='red')
ax2.set_xlabel("Time (s)")
ax2.set_ylabel("Rate of Climb (m/s)");

lines = [line1,line2]
labels = [line.get_label() for line in lines]

plt.axhline(y=roc_crit, color='black', linestyle='--')
plt.axvline(x=t_limit*60, color='black', linestyle='--')

plt.text(1470, 0.6, 'Critical VROC (m/s)', va='bottom', color='black')
plt.text(1470, 10, 'Service Ceiling (m)', va='bottom', color='black')

plt.plot(t_limit*60, roc_crit, marker='o',color='black')

plt.axis(xmin= 0,xmax=2000)
plt.legend(lines,labels,loc='right')
plt.show()

### Sensitivity Analysis ###

import matplotlib.pyplot as plt

P_SL = 320000 # initialize
r = 4.2 # initialize

P_SL_var = np.linspace(P_SL*.8,P_SL*1.2,20) # P_SL plus or minus 20%
percent_P_SL = np.linspace(-20,20,20)

percent_h = []
percent_ttc = []

for i in P_SL_var:
  P_SL = i
  sol = solve_ivp(climb_dyn,t_span,y0, max_step=1) # solve with RK45
  t_vals = sol.t # t values
  h_vals = sol.y[0] # h values
  roc_vals = sol.y[1] # v values
  above = (roc_vals >= roc_crit) # find when roc initially passes critical
  first_above = np.argmax(above) # find the first roc value past critical
  below = np.where((roc_vals <= roc_crit) & (np.arange(len(roc_vals)) > first_above))[0] # all points after climb where roc <= roc_crit
  i = below[0] # finds the first time roc falls below roc_crit
  h_temp = h_vals[i]
  t_temp = t_vals[i] / 60
  h_diff = (h_temp-h_limit)/((h_limit+h_temp)/2)*100
  t_diff = (t_temp-t_limit)/((t_limit+t_temp)/2)*100
  percent_h.append(h_diff)
  percent_ttc.append(t_diff)

### SENSITIVITY ANALYSIS PLOTTING ###

fig, ax1 = plt.subplots()

line1, = ax1.plot(percent_P_SL,percent_h,label= "Service_Ceiling",color='blue')
ax1.set_xlabel("Percent change in sea level turboshaft power")
ax1.set_ylabel("Percent change in service ceiling")

ax2 = ax1.twinx()
line2, = ax2.plot(percent_P_SL,percent_ttc,label= "TTC",color='red')
ax2.set_xlabel("Percent change in sea level turboshaft power")
ax2.set_ylabel("Percent change in TTC")

lines = [line1,line2]
labels = [line.get_label() for line in lines]

plt.legend(lines,labels,loc='right')
plt.show()

### PROGRAM VERIFICATION ###

t_eval = np.arange(0, 3601, 1)

sol = solve_ivp(fun=climb_dyn, t_span=(0, 3600), y0=[0, 0], method='RK23', max_step=1.0, t_eval=t_eval)

t_vals  = sol.t
h_vals  = sol.y[0]
roc_vals = sol.y[1]

above = (roc_vals >= roc_crit)
first_above = np.argmax(above)
below = np.where(roc_vals[first_above:] <= roc_crit)[0]
i = first_above + (below[0])

h_limit = h_vals[i]
t_limit = t_vals[i] / 60.0

print(f"Service-ceiling altitude ≈ {h_limit:.0f} m")
print(f"Threshold ROC TTC ≈ {t_limit:.1f} min")